version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tempest-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - ./backend:/code
  
  redis:
    image: redis:alpine

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tempest-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
      - ./frontend/node_modules:/code/node_modules
    stdin_open: true
    command: npm run start